// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqdvtnvvvgnnbfaydmmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZHZ0bnZ2dmdubmJmYXlkbW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTQzMjAsImV4cCI6MjA2ODY5MDMyMH0.KenSn7usOKnnJkd2BDOE-H1_GAyANeAvfP5Gf4H2kjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});